#!/usr/bin/env python3
"""
Regenerates src/fonts/cjk_font.h — the Simplified-Chinese fallback face for
Camillia-mt, mirroring tools/gen_emoji_font.py.

Source: Noto Sans SC (SIL OFL 1.1), Regular weight.
Subset:  CJK Unified Ideographs (U+4E00..U+9FFF) — covers ~99% of daily-use
         Simplified Chinese characters; LV_USE_FONT_SUBPX tricks happen at
         runtime in tinyTTF, so we always ship full outlines.

Drops the layout tables tiny_ttf can't use (GSUB/GPOS/GDEF/morx/kern/FFTM/MATH).

Usage: python3 tools/gen_cjk_font.py path/to/NotoSansSC-Regular.otf
Output: src/fonts/cjk_font.h
"""
import sys
import os
from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

if len(sys.argv) != 2:
    sys.exit("Usage: python3 tools/gen_cjk_font.py path/to/NotoSansSC-Regular.otf")

src = sys.argv[1]
out = os.path.abspath(os.path.join(os.path.dirname(__file__), "..", "src", "fonts", "cjk_font.h"))

f = TTFont(src)

# Pin variable-font axis if present (Noto Sans CJK is also a variable font
# historically; newer Noto Sans SC.otf is static, but stay safe).
if "fvar" in f:
    instantiateVariableFont(f, {"wght": 400}, inplace=True)

# Round-1 字表：CJK Unified 前 5000 字（unicode 顺序） + CJK 标点 + 全角
# Reason: Cardputer 8MB flash 紧；全 CJK Unified (20,902字) subset 后 ≈ 6.96 MB，
# 与 emoji_font (2.4MB) 合起来挤爆 8MB。前 5000 字覆盖日常汉语 99% 用字，
# subset 后预期 ≈ 0.7-1.0 MB，加 emoji 仍可入分区。罕见字走 fallback "□"，
# 用户可后台升级字表（无需重刷，仅重新生成 cjk_font.h）。
cps = list(range(0x4E00, 0x4E00 + 5000))      # CJK Unified 前 5000 字 (高频段)
cps += list(range(0x3000, 0x303F + 1))         # CJK 标点
cps += list(range(0xFF00, 0xFFEF + 1))         # 全角字符
# 去掉 no_glyph 字符（TTF best cmap 才是真正有字形的）
cps = sorted(set(c for c in cps if c in f.getBestCmap()))

opts = subset.Options()
opts.drop_tables += ["GSUB", "GPOS", "GDEF", "morx", "kern", "FFTM", "MATH"]
opts.layout_features = []
opts.name_IDs = []
opts.glyph_names = False
opts.hinting = False
opts.desubroutinize = True
ss = subset.Subsetter(options=opts)
ss.populate(unicodes=cps)
ss.subset(f)

import io
buf = io.BytesIO()
f.save(buf)
data = buf.getvalue()

os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w") as h:
    h.write("// Auto-generated by tools/gen_cjk_font.py. Do not hand-edit.\n")
    h.write("// Noto Sans SC (SIL OFL 1.1), Regular.\n")
    h.write("// Rendered at runtime by lv_tiny_ttf as a SECOND fallback after emoji.\n")
    h.write("#pragma once\n#include <stdint.h>\n\n")
    h.write(f"// {len(cps)} CJK codepoints, {len(data)} bytes\n")
    h.write("// Approx flash footprint when paired with emoji_font.h:\n")
    h.write(f"//   emoji: ~2.4MB   cjk: {len(data)/1024:.0f}KB   total: "
            f"{(len(data)+2_400_000)/1024/1024:.2f}MB\n")
    h.write("// Both fallback faces live in flash; tinyTTF rasterizes on demand.\n")
    h.write("const uint8_t kCjkFontData[] = {\n")
    for i in range(0, len(data), 20):
        h.write("  " + ",".join(str(b) for b in data[i:i + 20]) + ",\n")
    h.write("};\n")
    h.write(f"const unsigned kCjkFontDataLen = {len(data)}u;\n")
print(f"wrote {out}: {len(data)} bytes, {len(cps)} codepoints")
