#!/usr/bin/env python3
"""
Regenerates src/fonts/cjk_font.h — the Simplified-Chinese fallback face for
Camillia-mt.

Source: Source Han Sans SC (SIL OFL 1.1), Regular weight — the same design as
        Noto Sans CJK SC (Adobe/Google joint release).
Subset: the N most frequent Simplified-Chinese characters (Jun Da's Modern
        Chinese Character Frequency List, tools/junda_freq.txt) + CJK
        punctuation + fullwidth forms.

WHY THIS SIZE
-------------
16 MB boards (tdeck, tlora-pager-tft, heltec-v4, heltec-v4-vertical, m9,
mesh-deck, square) carry the FULL 9,903-character list (~2.4 MB of flash as
desubroutinized CFF outlines, ~240 B/codepoint at this depth). That only fits
because their OTA slots grew to 0x4E0000 (~5 MB) in partitions.csv /
partitions_16mb_fs.csv / partitions_pager_fs.csv — the mono emoji face those
slots used to share was only 776 KB of flash, so a full face never fit the old
3.125 MB slots. Boards must move to the grown tables via one full USB flash of
a factory image; after that, on-device OTA keeps working.

cardputer-cap is the exception: it is the one 8 MB flash and cannot take two
~5 MB slots. It uses partitions_cardputer.csv (0x3C0000 slots, the most an
8 MB part allows) and carries a 5,000-character face (cjk_font_small.h,
selected by -DCJK_FONT_SMALL in platformio.ini) — trimmed from 7,000 in
v4.8.3 to make room for the returning common-400 emoji face.

Pass N (and an output path) to cut a smaller face if flash pressure ever
returns; rare characters render as the missing-glyph box.

Drops the layout tables tiny_ttf can't use (GSUB/GPOS/GDEF/morx/kern/FFTM/MATH).

Font source note: cjk_font.h was last cut from Source Han Sans SC Regular
(CFF, `@fontpkg/source-han-sans-sc` on npmmirror — full-charset OTF, fetched
in seconds where GitHub/CDN raw downloads crawl). TrueType-flavored webfonts
of the same design cost ~254 B/codepoint and do not fit the budget.

Usage: python3 tools/gen_cjk_font.py path/to/SourceHanSansSC-Regular.otf [N] [out.h]
Output: src/fonts/cjk_font.h (default), or the given path
"""
import sys
import os
from fontTools import subset
from fontTools.ttLib import TTFont
from fontTools.varLib.instancer import instantiateVariableFont

FREQ_LIST = os.path.join(os.path.dirname(os.path.abspath(__file__)), "junda_freq.txt")

if len(sys.argv) not in (2, 3, 4):
    sys.exit("Usage: python3 tools/gen_cjk_font.py path/to/SourceHanSansSC-Regular.otf [N] [out.h]")

src = sys.argv[1]
ranked = []
with open(FREQ_LIST, encoding="utf-8") as f:
    for line in f:
        line = line.strip()
        if not line or line.startswith("#"):
            continue
        rank_s, ch = line.split()
        ranked.append(ch)
n_chars = int(sys.argv[2]) if len(sys.argv) >= 3 else len(ranked)
if n_chars > len(ranked):
    sys.exit(f"N={n_chars} exceeds the frequency list ({len(ranked)} chars).")
out = sys.argv[3] if len(sys.argv) == 4 else os.path.join(
    os.path.dirname(__file__), "..", "src", "fonts", "cjk_font.h")
out = os.path.abspath(out)

f = TTFont(src)

# Pin variable-font axis if present (SourceHanSansSC-Regular.otf is static,
# but stay safe).
if "fvar" in f:
    instantiateVariableFont(f, {"wght": 400}, inplace=True)

cmap = f.getBestCmap()

# Frequency-ranked Han characters, then CJK punctuation + fullwidth forms, plus
# the handful of halfwidth marks Chinese text routinely carries (curly quotes,
# dashes, ellipsis, middle dot). Only codepoints that actually have glyphs in
# the source font survive.
cps = [ord(c) for c in ranked[:n_chars]]
cps += list(range(0x3000, 0x303F + 1))          # CJK punctuation
cps += list(range(0xFF00, 0xFFEF + 1))          # fullwidth forms
cps += [0x00B7, 0x2013, 0x2014, 0x2018, 0x2019, 0x201C, 0x201D, 0x2026]
cps = sorted(set(c for c in cps if c in cmap))

opts = subset.Options()
opts.drop_tables += ["GSUB", "GPOS", "GDEF", "morx", "kern", "FFTM", "MATH"]
opts.layout_features = []
opts.name_IDs = []
opts.glyph_names = False
opts.hinting = False
opts.desubroutinize = True
ss = subset.Subsetter(options=opts)
ss.populate(unicodes=cps)
ss.subset(f)

import io
buf = io.BytesIO()
f.save(buf)
data = buf.getvalue()

os.makedirs(os.path.dirname(out), exist_ok=True)
with open(out, "w") as h:
    h.write("// Auto-generated by tools/gen_cjk_font.py. Do not hand-edit.\n")
    h.write("// Source Han Sans SC (SIL OFL 1.1), Regular — same design as Noto Sans CJK SC.\n")
    h.write("// Rendered at runtime by lv_tiny_ttf as the user-text fallback face.\n")
    h.write("#pragma once\n#include <stdint.h>\n\n")
    h.write(f"// {len(cps)} codepoints (top-{n_chars} frequency-ranked CJK + punctuation "
            f"+ fullwidth), {len(data)} bytes\n")
    h.write("// Rasterized on demand by tinyTTF; the data is flash-resident.\n")
    h.write("const uint8_t kCjkFontData[] = {\n")
    for i in range(0, len(data), 20):
        h.write("  " + ",".join(str(b) for b in data[i:i + 20]) + ",\n")
    h.write("};\n")
    h.write(f"const unsigned kCjkFontDataLen = {len(data)}u;\n")
print(f"wrote {out}: {len(data)} bytes, {len(cps)} codepoints")
