#!/usr/bin/env python3
# Regenerates src/fonts/emoji_font.h — the monochrome Noto Emoji face used as
# the LVGL fallback font for emoji rendering (see main_lvgl.cpp emoji plumbing).
#
# Source: Noto Emoji (SIL OFL 1.1). Two modes:
#   1) full face  — subset to the font's whole emoji cmap (v4.7.x behavior,
#      ~776 KB);
#   2) common subset — pass a list file (one emoji per line, '#' comments);
#      only the first N single-codepoint characters that actually exist in
#      the font's cmap are kept. ZWJ sequences and regional-indicator flag
#      pairs are skipped: the face drops GSUB, so those ligatures never
#      rendered anyway. Variation selectors (U+FE0E/U+FE0F) are stripped.
#
# Steps either way: drop layout/hint tables stb_truetype can't use, emit as a
# flash-resident C array.
#
# Usage: python3 tools/gen_emoji_font.py path/to/NotoEmoji.ttf [list.txt] [N]
import sys, os
from fontTools import subset
from fontTools.ttLib import TTFont

src = sys.argv[1]
list_path = sys.argv[2] if len(sys.argv) >= 3 else None
cap = int(sys.argv[3]) if len(sys.argv) >= 4 else 400
out = os.path.join(os.path.dirname(__file__), "..", "src", "fonts", "emoji_font.h")

f = TTFont(src)
if "fvar" in f:
    from fontTools.varLib.instancer import instantiateVariableFont
    instantiateVariableFont(f, {"wght": 400}, inplace=True)

cmap = f.getBestCmap()

if list_path:
    picked, seen, skipped = [], set(), 0
    with open(list_path, encoding="utf-8") as lf:
        for line in lf:
            line = line.split('#')[0].strip()
            for ch in line:
                if ch in "\ufe0e\ufe0f\u200d":
                    continue
                cp = ord(ch)
                if 0x1F1E6 <= cp <= 0x1F1FF:  # regional indicators: flag
                    continue                   # ligatures need GSUB, never rendered
                if cp in seen:
                    continue
                seen.add(cp)
                if cp not in cmap:
                    skipped += 1
                    continue
                picked.append(cp)
                if len(picked) >= cap:
                    break
            if len(picked) >= cap:
                break
    print(f"picked {len(picked)} codepoints from {list_path}")
    if skipped:
        print(f"skipped {skipped} codepoints not present in the font cmap")
    cps = picked
    mode_note = f"common subset ({cap} cap), list: tools/emoji_common.txt"
else:
    cps = sorted(cmap.keys())
    mode_note = "emoji cmap only"

opts = subset.Options()
opts.drop_tables += ['GSUB', 'GPOS', 'GDEF', 'morx', 'kern', 'FFTM', 'MATH']
opts.layout_features = []
opts.name_IDs = []
opts.glyph_names = False
opts.hinting = False
opts.desubroutinize = True
ss = subset.Subsetter(options=opts)
ss.populate(unicodes=cps)
ss.subset(f)

import io
buf = io.BytesIO(); f.save(buf); data = buf.getvalue()

with open(out, "w") as h:
    h.write("// Auto-generated by tools/gen_emoji_font.py. Do not hand-edit.\n")
    h.write("// Noto Emoji (SIL OFL 1.1), monochrome, wght=400.\n")
    h.write("// Rendered at runtime by lv_tiny_ttf as the Montserrat fallback font.\n")
    h.write(f"// Mode: {mode_note}.\n")
    h.write("#pragma once\n#include <stdint.h>\n\n")
    h.write(f"// {len(cps)} emoji codepoints, {len(data)} bytes\n")
    h.write("const uint8_t kEmojiFontData[] = {\n")
    for i in range(0, len(data), 20):
        h.write("  " + ",".join(str(b) for b in data[i:i+20]) + ",\n")
    h.write("};\n")
    h.write(f"const unsigned kEmojiFontDataLen = {len(data)}u;\n")
print("wrote", out, len(data), "bytes,", len(cps), "codepoints")
