#pragma once
// Full-pinyin IME engine over the 'PYI1' candidate table in
// src/fonts/pinyin_table.h (generated by tools/gen_pinyin_ime.py from the
// Rime pinyin-simp dictionary, Apache-2.0). Engine ported from
// Meshtastic-CardputerADV-CN (MIT, hansgao0422), reworked onto fixed
// buffers — no Arduino String in the lookup path, no heap churn per key.
//
// Behaviour matches the reference implementation: a composition of at most
// six letters prefix-matches the table's codes, collecting up to 45 ranked
// single hanzi; five candidates show per page; committing clears state. The
// engine only owns pinyin state — key routing lives with the caller, which
// decides what falls through to ordinary typing when the composition is
// empty (digits, arrows, Enter, Space keep their normal meanings).

#include <stddef.h>

namespace pinyin_ime {

constexpr int kMaxCandidates = 45;  // reference cap: ni collects its longer
                                    // prefixes' candidates too (ni, nian,
                                    // niao, ...) until the cap
constexpr int kPageSize = 5;
constexpr int kMaxComposition = 6;

bool enabled();                     // CN/EN mode
void setEnabled(bool on);           // clears composition on change
bool toggle();                      // returns the new state
void reset();                       // clears composition + candidates,
                                    // keeps the CN/EN mode

const char *composition();          // current letters, "" when none
bool hasComposition();

int candidateCount();               // absolute candidate total
const char *candidate(int index);   // UTF-8 hanzi, nullptr when out of range
int page();                         // 0..pageCount()-1
int pageCount();
bool nextPage();
bool prevPage();

bool feedLetter(char c);            // 'a'..'z' (upper-case folded); false when
                                    // the composition is already at its cap
bool feedBackspace();               // drops one letter; false when empty
bool commitIndex(int index, char out[4]);  // absolute index; UTF-8 + NUL;
                                           // clears state on success
bool commitFirst(char out[4]);      // first candidate of the current page

}  // namespace pinyin_ime
