#pragma once
// Wubi-86 IME engine over the 'WBI2' candidate table in
// src/fonts/wubi_table.h (generated by tools/gen_wubi_ime.py from the
// Rime wubi86 dictionary — LGPL-3.0). On first use the table is
// inflated from raw-DEFLATE into a single PSRAM buffer; the caller (UI)
// only has to call wubi_ime::ensureInit() before the first composition.
//
// Behaviour: a composition of up to four letters (a-y) prefix-matches the
// sorted code table, collecting up to kMaxCandidates ranked single-hanzi
// or multi-hanzi phrase entries; kPageSize candidates show per page (5,
// or 3 on the Cardputer's narrow panel). Multi-word entries (up to 9 CJK
// chars = 27 UTF-8 bytes) are copied verbatim at commit time.
//
// Z is NOT a Wubi-86 code key (wildcard on PC engines). feedLetter
// rejects 'z' so the caller passes it through as plain ASCII input.

#include <stddef.h>

namespace wubi_ime {

constexpr int kMaxCandidates = 45;
#if defined(DEVICE_CARDPUTER_LORA_HAT)
constexpr int kPageSize = 3;
#else
constexpr int kPageSize = 5;
#endif
constexpr int kMaxComposition = 4;
constexpr int kMaxCandidateBytes = 28;   // 9 CJK chars (27 bytes) + NUL

// Returns true if the table has successfully been inflated (always true
// once setup() completes on PSRAM boards).
bool ready();

// Inflate + validate the table once; safe to call multiple times. Returns
// false if PSRAM allocation or decompression failed (IME falls through).
bool ensureInit();

bool enabled();
void setEnabled(bool on);
bool toggle();
void reset();

const char *composition();
bool hasComposition();

int candidateCount();
// candidate() returns a NUL-terminated UTF-8 ptr into the PSRAM table.
const char *candidate(int index);

int page();
int pageCount();
bool nextPage();
bool prevPage();

// Returns true if the engine consumed the key (part of a code). False
// means the caller should type it as a plain character.
bool feedLetter(char c);
bool feedBackspace();

// commitIndex writes the selected candidate (NUL-terminated, <= 28 bytes)
// to `out` and resets composition. out must be >= kMaxCandidateBytes.
bool commitIndex(int index, char *out);
bool commitFirst(char *out);

}  // namespace wubi_ime
