#pragma once
// Wubi-86 IME engine over the 'WBI1' candidate table in
// src/fonts/wubi_table.h (generated by tools/gen_wubi_ime.py from the
// Rime wubi86 dictionary — Jidian-86 full codes + level-1/2 jianma,
// LGPL-3.0). Same engine shape as the old pinyin_ime (ported from
// Meshtastic-CardputerADV-CN, MIT, hansgao0422), reworked onto fixed
// buffers — no Arduino String in the lookup path, no heap churn per key.
//
// Behaviour: a composition of at most four letters prefix-matches the
// table's codes, collecting up to 45 ranked single hanzi; kPageSize
// candidates show per page (5, or 3 on the Cardputer's narrow panel);
// committing clears state. The classic jianma live in the table as short
// codes, so a key's level-1 char ranks first and two-key prefixes reach
// their level-2 chars. Z is not a Wubi-86 code key (wildcard on real
// engines) — feedLetter rejects it so the letter falls through to plain
// typing. The engine only owns composition state — key routing lives with
// the caller, which decides what falls through to ordinary typing when the
// composition is empty (digits, arrows, Enter, Space keep their normal
// meanings).

#include <stddef.h>

namespace wubi_ime {

constexpr int kMaxCandidates = 45;  // cap on the prefix run kept for paging
#if defined(DEVICE_CARDPUTER_LORA_HAT)
// The Cardputer's 240 px panel gives the bar ~200 px after the toggle button;
// five candidates plus the code echo need ~220 px, which wrapped into two
// clipped lines inside the 18 px bar. Three per page fits one line; the rest
// stay reachable through page keys.
constexpr int kPageSize = 3;
#else
constexpr int kPageSize = 5;
#endif
constexpr int kMaxComposition = 4;  // wubi-86 full codes are 1-4 keys (a-y)

bool enabled();                     // CN/EN mode
void setEnabled(bool on);           // clears composition on change
bool toggle();                      // returns the new state
void reset();                       // clears composition + candidates,
                                    // keeps the CN/EN mode

const char *composition();          // current letters, "" when none
bool hasComposition();

int candidateCount();               // absolute candidate total
const char *candidate(int index);   // UTF-8 hanzi, nullptr when out of range
int page();                         // 0..pageCount()-1
int pageCount();
bool nextPage();
bool prevPage();

bool feedLetter(char c);            // 'a'..'y' (upper-case folded, z rejected);
                                    // false when the composition is at its cap
bool feedBackspace();               // drops one letter; false when empty
bool commitIndex(int index, char out[4]);  // absolute index; UTF-8 + NUL;
                                           // clears state on success
bool commitFirst(char out[4]);      // first candidate of the current page

}  // namespace wubi_ime
